name: Go CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build all services
        run: |
          for svc in api-gateway auth-service habits-service stats-service notification-service bot-service worker-service; do
            cd $svc && go build -v ./... && cd ..
          done

      - name: Run tests for all services
        run: |
          for svc in api-gateway auth-service habits-service stats-service notification-service bot-service worker-service; do
            cd $svc && go test -v -race -cover ./... && cd ..
          done

      - name: Lint (golangci-lint)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59
